#  makefile for BDIFF.EXE   --   'marikaz'
#
# /DDEBUG  - create debug version
# /DVDT    - include version number

ASM=tasm
LINK=tlink

!if $d(DEBUG)
ASMFLAGS=/m /zi
LINKFLAGS=/v
!else
ASMFLAGS=/m
LINKFLAGS=/x
!endif

!if $d(VDT)
ASMFLAGS=$(ASMFLAGS) /dVDT
!endif

OUTDIR=bin
INCDIR=inc

OBJ=main.obj garg.obj comp.obj comm.obj
INC=$(INCDIR)\bdiff.inc $(INCDIR)\form.inc
EXE=$(OUTDIR)\bdiff.exe

all: $(OUTDIR) $(EXE)

$(OUTDIR):
           @if not exist $(OUTDIR) mkdir $(OUTDIR)

main.obj: main.asm $(INC)
          $(ASM) $(ASMFLAGS) main.asm
garg.obj: garg.asm $(INC)
          $(ASM) $(ASMFLAGS) garg.asm
comp.obj: comp.asm $(INC)
          $(ASM) $(ASMFLAGS) comp.asm
comm.obj: comm.asm $(INC)
          $(ASM) $(ASMFLAGS) comm.asm

$(EXE): $(OBJ) $(INC)
        $(LINK) $(LINKFLAGS) $(OBJ),$(EXE)
clean:
       del $(OUTDIR)\*.map
       del $(OUTDIR)\*.exe
       del *.obj
